### PR TITLE
Added minesLake.prefab

### PR DESCRIPTION
**Pull request by billxu1401**
Added a lake in mine

terasology-181208112939-1366x705

Spawned lake (left is spawned template, right is the original one):

terasology-181208113509-1366x705

### CODE REVIEW

**Comment by Cervator** [comment]
Looks good! But doesn't work. Check the GCI task for details and see other working corridor pieces for clues why :-)

**Comment by Cervator** [comment]
Hey again. So there's some sort of weird disconnect here. What I was hinting at previously is that the other working corridors have more stuff in their json than yours, which indicate how the segment fits into the existing structure line. See for instance https://github.com/Terasology/GooeysQuests/blob/master/assets/prefabs/structures/mines/minesCorridor/minesCoalCorridor.prefab

All those extra details are what makes the system function. You don't have any of those. Yet you have the screenies - do you have those details in your local file yet you somehow end up submitting something different on GitHub? Or are you solely placing those segments manually? I'm not sure what's happening. It may be better to coordinate on Discord sometime with somebody else who has worked in this area

**Comment by billxu1401** [comment]
@Cervator It works now :)

**Comment by Cervator** [comment]
It sure does - thanks!

**Pull request merged**
