### PR TITLE
Added dwarf halls dungeon type

### PR DESCRIPTION
**Pull request by MaxBorsch**
Adds another dungeon type, Dwarf Halls (Bridges?).

Wait for Gooey to spawn/respawn (60 seconds) and ask you if you want to explore dwarf halls. If he says "dungeon" instead of "dwarf halls" then that is the legacy dungeon, wait for him to respawn.

Requires ChiselBlocks which is not yet added for public release.

**Sort of like this, but with more variation / structures and underground:**

### CODE REVIEW

**Comment by Cervator** [comment]
Awesome! Tried it out and was able to visit some dwarf halls that seem to span quite some distance! :D

There was a small conflict about the move of the dungeon tomb, bit weird how that came about. I fixed it in a branch - https://github.com/Terasology/GooeysQuests/tree/testconflictfix

Not merging just yet since we should add ChiselBlocks to the lineup so it'll be available. Need to add some more stuff so will do that soon. Also gives @flo a chance to check out the awesome here :-)

For either of you: think we can find a way for Gooey to offer *any* quest? I think I talked to Max about this a bit. Hard to test a specific structure when Gooey keeps offering you the other.

**Comment by MaxBorsch** [comment]
@Cervator We could add a commands system, stuff like `spawngooey DwarfHallsQuest`. Currently, you can test a specific dungeon by grabbing an item of the dungeon entrance and placing it yourself.
`give dwarfHallsEntranceViaMountain`
and then place it at a mountainside, it'll spawn the rest of the dungeon for you.

**Comment by flo** [comment]
Very cool. 

Some idears I had about determining what quests you are interested:
* Gooey offers a "I am not interested in thsi quest" option. If selected gooey will no longer offer you that quest. It's easy to implement and might be sufficient for now while we have just 2 quets
* Gooey offers you a "I am interested in ..." option which opens a dialog that allows you to select which quest(s) you want to do. Previously rejected quests could here be reaquired. In the future that quest selection dialog could also show teasier images, give tipps where gooey will allow you to start the quest, and maybe even may list requirements for the quest before it can be started.
* To allow the user to change his mind we would also have an option for the player to summon gooey. e.g. via "gooey" command.
* Another way to give players control over quests would be items. E.g. there could be a "Map to dwarf halls" item. While you have it in inventory gooey will offer you "dwarf hall" quests. Gooey will offer you the quest in exchange for 1 instance of the item. Nice thing about this approach would be that we would have a new kind of loot and an still an easy way to test quests. Also good would be that we could have quests that offer more rewards than other quests but are more rare. E.g. a "map to lava cave with diamonds" might be a rare item. While "Map to stone dungeon" might be very common. To new players we could give a item "Note from Gooey" that will make gooey offer them a simple quest to find a chest with some basic items and some basic quests.

**Comment by flo** [comment]
@MaxBorsch do you have an IRC account or are around in slack?

**Comment by MaxBorsch** [comment]
@flo I'm around on slack, same name. I also have IRC but I haven't logged on recently because I've been using Slack.

**Comment by flo** [comment]
@Cervator just added ChiselBlocks to the lineup. So now I can merge this :D

**Pull request merged**
