### PR TITLE
Damageable skeleton & lava corridor fix

### PR DESCRIPTION
**Pull request by MaxBorsch**
Made skeleton killable / adjusted hitbox size.
Added ground blocks condition to lava corridor.

### CODE REVIEW

**Comment by Cervator** [comment]
Thanks! No more immortal skeleton, woohoo

**Comment by flo** [comment]
@MaxBorsch, @Cervator  The skeleton walks now in the air. I probably have to revert the skeleton change.

**Comment by MaxBorsch** [comment]
@flo One second that's because I made the skeeltons hitbox bigger (it scaled from the center though so it's floating) I'll undo it in a few seconds.

**Comment by MaxBorsch** [comment]
@flo Is there a way to move the hitbox up and keep the mesh down? If I change it back you'll have to hit the skeleton in the legs to damage it.

**Pull request merged**
